import React from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowLeft, ScrollText } from 'lucide-react';

const TermsOfService: React.FC = () => {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-300 font-sans selection:bg-orange-500 selection:text-white">
       <nav className="border-b border-white/10 bg-slate-950/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
            <Link to="/" className="flex items-center gap-2 font-bold text-xl tracking-tight text-white hover:opacity-80 transition-opacity">
                <span className="text-orange-500">ORENGEN</span>
                <span>NEXUS</span>
            </Link>
            <Link to="/" className="text-sm font-medium hover:text-white flex items-center gap-2">
                <ArrowLeft size={16} /> Back to Home
            </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-20">
         <div className="mb-12">
            <div className="w-16 h-16 bg-orange-500/10 rounded-2xl flex items-center justify-center text-orange-500 mb-6">
                <ScrollText size={32} />
            </div>
            <h1 className="text-4xl md:text-5xl font-extrabold text-white mb-6">Terms of Service</h1>
            <p className="text-lg text-slate-400">Effective Date: March 15, 2024</p>
        </div>

        <div className="prose prose-invert prose-lg max-w-none">
            <p>
                Welcome to OrenGen Nexus. By accessing or using our platform, you agree to be bound by these Terms of Service. If you do not agree, you may not use our services.
            </p>

            <h3>1. Acceptable Use</h3>
            <p>
                You agree to use the Nexus Operating System only for lawful purposes. You are prohibited from:
            </p>
            <ul>
                <li>Using AI Agents to generate hate speech, harassment, or illegal content.</li>
                <li>Attempting to reverse engineer or breach the security of the Nexus infrastructure.</li>
                <li>Reselling access to the platform without an Enterprise License.</li>
            </ul>

            <h3>2. Intellectual Property</h3>
            <p>
                <strong>Your Content:</strong> You retain full ownership of any assets (code, copy, images) generated by you or the AI Agents within your projects.
                <br />
                <strong>Our Platform:</strong> OrenGen Systems retains all rights to the underlying software, agent architectures, and interface designs.
            </p>

            <h3>3. Service Availability (SLA)</h3>
            <p>
                For Enterprise customers, we guarantee 99.9% uptime. For Standard plans, we strive for high availability but do not offer financial guarantees for downtime caused by third-party API outages (e.g., OpenAI, Google Cloud).
            </p>

            <h3>4. Liability Limitation</h3>
            <p>
                OrenGen Systems is not liable for any indirect, incidental, or consequential damages arising from the use of our AI suggestions. You are responsible for reviewing all AI-generated output before deployment.
            </p>

            <h3>5. Termination</h3>
            <p>
                We reserve the right to suspend or terminate your account if you violate these terms, specifically regarding the "Acceptable Use" policy.
            </p>
        </div>
      </main>

      <footer className="border-t border-white/10 py-12 text-center text-slate-500 text-sm">
         &copy; {new Date().getFullYear()} OrenGen Systems. All rights reserved.
      </footer>
    </div>
  );
};

export default TermsOfService;